spring.application.name=botTelegram

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/botTelegram}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

telegram.bot.username=${TELEGRAM_BOT_USERNAME:it_job_parser_bot}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.admin-id=${TELEGRAM_BOT_ADMIN_ID:739564013}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://127.0.0.1:11434}
spring.ai.ollama.embedding.model=${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
spring.ai.ollama.embedding.options.keep-alive=-1
spring.ai.ollama.embedding.options.num-thread=16
spring.ai.ollama.embedding.request-timeout=60000

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

mts.api.key=${MTS_API_KEY}

parsers.disabled=${PARSERS_DISABLED:}

logging.charset.console=UTF-8
logging.charset.file=UTF-8

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
spring.jpa.open-in-view=false